#!/usr/bin/env bash
# Build the mobile-playable Web (HTML5) export of the Crow Godot port.
# Output: output/web/ (single-threaded build — serves from any static host,
# no COOP/COEP headers required, works in mobile browsers).
#
# Usage: bash godot/tools/build_web.sh
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"      # godot/
ROOT="$(cd "$HERE/.." && pwd)"                               # repo root
GODOT="${GODOT:-godot}"
OUT="$ROOT/output/web"

mkdir -p "$OUT"

# Bake a build stamp shown in the MainMenu corner so phone refreshes are
# visibly confirmed during fast iteration.
#
# CROW_BUILD_COMMIT lets CI stamp the commit actually being built. Locally we
# fall back to HEAD, which is the *parent* of the commit that will carry this
# build — so a local build's stamp is off by one until it is committed. CI is
# the source of truth for a deployed stamp.
COMMIT="${CROW_BUILD_COMMIT:-$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo dev)}"
printf '{"builtAt":"%s","commit":"%s"}\n' "$(date -u +%Y-%m-%dT%H:%MZ)" "$COMMIT" > "$HERE/build_info.json"

"$GODOT" --headless --path "$HERE" --import >/dev/null 2>&1 || true
"$GODOT" --headless --path "$HERE" --export-release "Web" "$OUT/index.html"

# ── content-addressed payload ────────────────────────────────────────────────
#
# Godot exports fixed filenames (index.wasm, index.pck), which forces the cache
# policy to be "revalidate every launch": the browser has to ask whether the file
# it holds is still current, because the name alone cannot say. Stamping a
# content hash into the names removes that question, so the payload can be served
# `immutable` and a returning player transfers ZERO bytes for it.
#
# One id derived from both files rather than a hash per file, because Godot's
# loader builds every path from a single `executable` name: it asks for
# <executable>.wasm, <executable>.pck and <executable>.audio.worklet.js. One id
# keeps that contract intact.
stamp_build_id() {
	local id
	id="$(cat "$OUT/index.wasm" "$OUT/index.pck" | sha256sum | cut -c1-12)"
	echo "content id: $id"

	for ext in wasm pck js audio.worklet.js; do
		[ -f "$OUT/index.$ext" ] || continue
		mv "$OUT/index.$ext" "$OUT/index.$id.$ext"
	done

	# Rewrite the shell: the engine config's `executable`, the fileSizes keys it
	# checks against, and the <script src> that bootstraps it.
	python3 - "$OUT/index.html" "$id" <<'REWRITE'
import re, sys
path, build_id = sys.argv[1], sys.argv[2]
html = open(path).read()
html = html.replace('"executable":"index"', f'"executable":"index.{build_id}"')
html = re.sub(r'"index\.(pck|wasm)"', lambda m: f'"index.{build_id}.{m.group(1)}"', html)
html = html.replace('src="index.js"', f'src="index.{build_id}.js"')
open(path, 'w').write(html)
REWRITE

	# index.html itself must never be cached: it is the only thing that knows
	# which hashed payload belongs to this build.
	printf '%s\n' "$id" > "$OUT/build_id.txt"
}

# The <head> scripts are not Godot resources, so the export does not emit them.
# Copy them in beside the shell that references them.
stamp_build_id

cp "$ROOT/deploy/web/crow-errors.js" "$OUT/crow-errors.js"
cp "$ROOT/deploy/web/crow-focus.js" "$OUT/crow-focus.js"

# Portrait hint. The game is landscape-only (project.godot orientation=0, stretch
# keep), so a child holding the iPad upright gets a letterboxed strip and no
# explanation — and cannot read one anyway. Injected here because index.html is
# regenerated by the Godot export on every build.
python3 - "$OUT/index.html" <<'ROTATE'
import sys
path = sys.argv[1]
html = open(path).read()
if 'crow-rotate' not in html:
    overlay = ('<div id="crow-rotate" aria-hidden="true">'
               '<span>\N{MOBILE PHONE WITH RIGHTWARDS ARROW AT LEFT}</span>'
               'Turn your tablet sideways'
               '</div>')
    html = html.replace('<body>', '<body>' + overlay, 1)
    open(path, 'w').write(html)
ROTATE

# build_info.json is inside the pck for main_menu.gd, but crow-errors.js fetches
# it over HTTP to tag reports with the build, so it also needs to sit next to
# index.html.
cp "$HERE/build_info.json" "$OUT/build_info.json"

# NOTE: the payload is NOT precompressed here. Caddy serves precompressed
# .gz files when they exist (deploy/web/Caddyfile -> file_server precompressed),
# and those are generated inside the Docker image build instead. Committing ~23 MB
# of .gz alongside the ~53 MB payload would double what every clone carries, for
# bytes that the image can regenerate in a second.

# Remove any payload from a previous build id: they are immutable and would
# otherwise accumulate in the deployed image forever.
find "$OUT" -maxdepth 1 -name 'index.*.wasm' -o -maxdepth 1 -name 'index.*.pck' \
	-o -maxdepth 1 -name 'index.*.js' | while read -r stale; do
	case "$stale" in *"$(cat "$OUT/build_id.txt" 2>/dev/null)"*) ;; *) rm -f "$stale" ;; esac
done

# Record what this export was built FROM. `npm run validate` and the godot CI job
# recompute the same hash and fail if the committed export no longer matches
# godot/**. Content addressing already busts caches; it does NOT catch staleness,
# because an export built from old sources still gets a perfectly valid
# content-addressed name. output/web is what Railway serves and it drifted a whole
# feature behind once. See tools/godot_export_fingerprint.mjs for why a hash and
# not a timestamp.
node "$ROOT/tools/write_export_fingerprint.mjs" "$ROOT"

echo "Web build written to $OUT/"
echo "Play locally:  (cd $OUT && python3 -m http.server 8060)  then open http://<this-machine-ip>:8060"
