/**
 * Problem catalog generator — the bridge from the authored pools to analytics.
 *
 * The server's `attempts` table stores problem_id but nothing about what kind
 * of problem it was, and the pools never leave the client. This emits
 * server/data/problem_catalog.json: problem_id -> { d: domain, k: kind },
 * where kind is the presentation subgroup a parent thinks in:
 *
 *   equation     - bare or framed arithmetic ("3 + 4 = ?", "What is 35 - 14?")
 *   word_problem - a story ("20 birds sit on a branch. 6 fly away. ...")
 *   visual       - count-the-objects prompts (dot strings, "How many dots?")
 *
 * Word problems are detected with the SAME table the runtime uses
 * (math-kernel's parseWordedArithmetic), so the analytics label can never
 * disagree with what the game itself considers a worded prompt. A poolsHash
 * over the source pools lets `npm run validate` fail when the catalog is
 * stale instead of letting the parent report silently misclassify.
 *
 * The output is a generated TypeScript module (not a JSON asset) because the
 * API's Docker image ships only tsc-compiled src/ — a data file would need
 * Dockerfile surgery, a .ts module survives the existing build untouched.
 *
 * Run: npx tsx tools/gen_problem_catalog.ts
 */
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { parseWordedArithmetic } from '../math-kernel/math/wordedArithmetic';

const ROOT = resolve(join(__dirname, '..'));
const MATH_DIR = join(ROOT, 'godot', 'data', 'math');
const OUT_PATH = join(ROOT, 'server', 'src', 'generated', 'problemCatalog.ts');

type Kind = 'equation' | 'word_problem' | 'visual';

interface PoolProblem {
    id: string;
    domain: string;
    prompt: { text: string };
}

/** A run of count-me objects: dots, bullets, or repeated single glyphs. */
const VISUAL_PROMPT = /(?:count these|how many (?:dots|stars|circles|objects))|(?:[.●○•*]\s+){2,}[.●○•*]/i;

export function classifyKind(domain: string, promptText: string): Kind {
    if (parseWordedArithmetic(promptText) !== null) return 'word_problem';
    if (domain === 'counting') return 'visual';
    if (VISUAL_PROMPT.test(promptText)) return 'visual';
    return 'equation';
}

export function buildCatalog(): { poolsHash: string; problems: Record<string, { d: string; k: Kind }> } {
    const files = readdirSync(MATH_DIR).filter(f => f.endsWith('.json')).sort();
    const hash = createHash('sha256');
    const problems: Record<string, { d: string; k: Kind }> = {};
    const census: Record<string, number> = {};

    for (const file of files) {
        const raw = readFileSync(join(MATH_DIR, file), 'utf-8');
        hash.update(file).update('\0').update(raw);
        const pool = JSON.parse(raw) as { problems: PoolProblem[] };
        for (const problem of pool.problems) {
            const kind = classifyKind(problem.domain, problem.prompt.text);
            problems[problem.id] = { d: problem.domain, k: kind };
            census[`${problem.domain}/${kind}`] = (census[`${problem.domain}/${kind}`] ?? 0) + 1;
        }
    }

    console.log('problem catalog census:');
    for (const key of Object.keys(census).sort()) {
        console.log(`  ${key.padEnd(32)} ${census[key]}`);
    }
    return { poolsHash: hash.digest('hex'), problems };
}

if (require.main === module) {
    const catalog = buildCatalog();
    mkdirSync(join(ROOT, 'server', 'src', 'generated'), { recursive: true });
    const module_ = [
        '// GENERATED by tools/gen_problem_catalog.ts — do not edit by hand.',
        '// Freshness against godot/data/math/** is enforced by npm run validate.',
        'export interface CatalogEntry { readonly d: string; readonly k: \'equation\' | \'word_problem\' | \'visual\'; }',
        `export const POOLS_HASH = ${JSON.stringify(catalog.poolsHash)};`,
        `export const PROBLEM_CATALOG: Record<string, CatalogEntry> = ${JSON.stringify(catalog.problems)};`,
        '',
    ].join('\n');
    writeFileSync(OUT_PATH, module_);
    console.log(`Wrote ${OUT_PATH} (${Object.keys(catalog.problems).length} problems)`);
}
