/**
 * Grade-expectations generator — Icelandic school grades into the API build.
 *
 * The canonical mapping (which curriculum-ladder step corresponds to the end
 * of which Icelandic school grade, with a source for every milestone) lives in
 * godot/data/curriculum/grade_expectations.json and is documented in
 * docs/GRADE_EXPECTATIONS.md. The server needs it to turn a child's birth year
 * into "ahead / on track / practice together" per domain, and the API's Docker
 * image ships only tsc-compiled src/ — so, exactly like the problem catalog,
 * the data is emitted as a generated TypeScript module with a freshness hash
 * that `npm run validate` checks.
 *
 * Run: npx tsx tools/gen_grade_expectations.ts
 */
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const ROOT = resolve(join(__dirname, '..'));
const SRC_PATH = join(ROOT, 'godot', 'data', 'curriculum', 'grade_expectations.json');
const OUT_PATH = join(ROOT, 'server', 'src', 'generated', 'gradeExpectations.ts');

interface Milestone {
    endOfGrade: number;
    step: number;
    covers: string;
    basis: string;
    source: string;
}

interface GradeExpectationsFile {
    meta: { schoolYearBoundaryMonth: number };
    domains: Record<string, Milestone[]>;
}

export function build(): { hash: string; data: GradeExpectationsFile } {
    const raw = readFileSync(SRC_PATH, 'utf-8');
    const parsed = JSON.parse(raw) as GradeExpectationsFile;

    for (const [domain, milestones] of Object.entries(parsed.domains)) {
        let lastGrade = 0;
        let lastStep = -1;
        for (const m of milestones) {
            if (m.endOfGrade <= lastGrade || m.step <= lastStep) {
                throw new Error(`${domain}: milestones must strictly increase in grade and step`);
            }
            lastGrade = m.endOfGrade;
            lastStep = m.step;
        }
        if (milestones.length === 0) throw new Error(`${domain}: no milestones`);
    }
    const month = parsed.meta.schoolYearBoundaryMonth;
    if (!Number.isInteger(month) || month < 1 || month > 12) {
        throw new Error(`schoolYearBoundaryMonth out of range: ${month}`);
    }

    return { hash: createHash('sha256').update(raw).digest('hex'), data: parsed };
}

if (require.main === module) {
    const { hash, data } = build();
    const compact = {
        schoolYearBoundaryMonth: data.meta.schoolYearBoundaryMonth,
        domains: Object.fromEntries(
            Object.entries(data.domains).map(([domain, milestones]) => [
                domain,
                milestones.map(m => ({ endOfGrade: m.endOfGrade, step: m.step })),
            ]),
        ),
    };
    mkdirSync(join(ROOT, 'server', 'src', 'generated'), { recursive: true });
    writeFileSync(OUT_PATH, [
        '// GENERATED by tools/gen_grade_expectations.ts — do not edit by hand.',
        '// Source of truth: godot/data/curriculum/grade_expectations.json',
        '// (provenance and research notes: docs/GRADE_EXPECTATIONS.md).',
        '// Freshness is enforced by npm run validate.',
        'export interface GradeMilestone { readonly endOfGrade: number; readonly step: number; }',
        `export const GRADE_EXPECTATIONS_HASH = ${JSON.stringify(hash)};`,
        `export const SCHOOL_YEAR_BOUNDARY_MONTH = ${compact.schoolYearBoundaryMonth};`,
        `export const GRADE_MILESTONES: Record<string, readonly GradeMilestone[]> = ${JSON.stringify(compact.domains)};`,
        '',
    ].join('\n'));
    console.log(`Wrote ${OUT_PATH} (${Object.keys(compact.domains).length} domains)`);
}
