/**
 * Ship the game's lane weights into the API image.
 *
 * The ladder tuning surface recommends moving weight from one selection lane to
 * another, and a recommendation whose "from" is invented is worse than none --
 * an owner would apply a change against numbers the game does not use. So it has
 * to read the real `laneWeights`.
 *
 * It cannot read them from disk at runtime: deploy/api/Dockerfile copies only
 * `server/`, so `godot/data/tuning/math_tuning.json` does not exist in the
 * running image and the endpoint would answer 500 in production while working
 * perfectly on a developer's checkout. That is exactly the class of bug this
 * repo generates `problemCatalog.ts` to avoid, so this follows the same pattern:
 * generate at build time, carry a hash, and let `npm run validate` fail when the
 * copy drifts from the source.
 *
 * Run: npx tsx tools/gen_ladder_weights.ts   (npm run validate checks freshness)
 */
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE = join(ROOT, 'godot', 'data', 'tuning', 'math_tuning.json');
const OUT = join(ROOT, 'server', 'src', 'generated', 'ladderWeights.ts');

const raw = readFileSync(SOURCE, 'utf-8');
const tuning = JSON.parse(raw) as { laneWeights: Record<string, number> };
if (!tuning.laneWeights || Object.keys(tuning.laneWeights).length === 0) {
    throw new Error(`${SOURCE} has no laneWeights to generate from.`);
}

const module_ = [
    '// GENERATED by tools/gen_ladder_weights.ts -- do not edit.',
    '//',
    '// The selection lane weights the game actually ships, copied in at build',
    '// time because the API image does not contain godot/data. `npm run validate`',
    "// fails if this drifts from godot/data/tuning/math_tuning.json.",
    `export const TUNING_HASH = ${JSON.stringify(createHash('sha256').update(raw).digest('hex'))};`,
    `export const LANE_WEIGHTS: Record<string, number> = ${JSON.stringify(tuning.laneWeights)};`,
    '',
].join('\n');

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, module_);
console.log(`Wrote ${OUT} (${Object.keys(tuning.laneWeights).length} lanes)`);
