/**
 * Fingerprint the sources that feed the committed Godot web export.
 *
 * `railway.json` -> `deploy/web/Dockerfile` copies `output/web` straight into
 * Caddy, so WHATEVER IS IN THAT DIRECTORY IS THE LIVE GAME. It is produced by
 * running `bash godot/tools/build_web.sh` by hand and committing a ~14MB pack
 * plus a ~34MB wasm, and nothing checked that it matched `godot/**`. The
 * deployment silently drifted a whole feature behind the source once, and cost a
 * play session before anyone noticed.
 *
 * WHY A HASH AND NOT A TIMESTAMP
 * ------------------------------
 * The obvious check is "is index.pck older than the newest file under godot/".
 * That cannot work: git does not preserve mtimes, so a fresh clone stamps every
 * file with the checkout time and the comparison becomes noise. Content is the
 * only thing that survives a clone, so the build records a hash of its inputs
 * and `npm run validate` recomputes it.
 *
 * There was a sibling doing this for the browser-smoke report
 * (tools/math_artifact_fingerprint.mjs); it was deleted in aed28a2 and this
 * comment outlived it by three commits. `npm run validate` names every
 * fingerprint tool it actually runs.
 *
 * WHAT IS DELIBERATELY EXCLUDED
 * -----------------------------
 *   godot/build_info.json  a build stamp containing a timestamp, rewritten on
 *                          every build. Including it would make the fingerprint
 *                          change for reasons that are not source changes.
 *   godot/tests/**         never exported; a test edit does not stale the build.
 *   godot/tools/**         the build script itself is not shipped.
 *   any .import sidecar     regenerated by `godot --import`, so they churn
 *                          without the asset having changed.
 *   any .md under godot/    documentation is not a Godot resource and the preset
 *                          exports `all_resources`, so it cannot reach the pck.
 *
 * THE PCK IS NOT BYTE-REPRODUCIBLE, AND THIS MATTERS
 * --------------------------------------------------
 * Measured 2026-08-25: two consecutive `build_web.sh` runs on an unchanged tree
 * produce pck files of identical SIZE and different CONTENT — about 197 KB of
 * 14.3 MB differs. `.godot/uid_cache.bin` and `global_script_class_cache.cfg`
 * are byte-stable across those runs, so the variation is inside the packing
 * itself, and the wasm is unaffected.
 *
 * Two consequences, and the second one is a correction:
 *
 *  1. This fingerprint hashes SOURCE FILES, never the artifact, so it is immune.
 *     That was a lucky design choice rather than a considered one, and it is the
 *     reason the freshness gate works at all.
 *  2. **You cannot learn anything about what feeds the pck by editing something
 *     and diffing pck hashes.** An earlier pass in this repo concluded that
 *     GDScript comment text reaches the pck bytes — and therefore that
 *     normalizing comments out of this fingerprint would make it lie — on
 *     exactly that experiment. The experiment was invalid; the hash changes on a
 *     no-op rebuild. Whether comments actually reach the bytes is UNKNOWN, and
 *     answering it needs a deterministic comparison (extract both pcks and diff
 *     the stored files), not a hash.
 *
 * It also means every rebuild rewrites the committed artifact whether or not
 * anything changed, which makes the committed-export cost worse than it looks.
 */
import { createHash } from 'crypto';
import { readFileSync } from 'fs';
import { resolve } from 'path';
import fg from 'fast-glob';

export const GODOT_EXPORT_SOURCE_PATTERNS = [
    'godot/project.godot',
    'godot/export_presets.cfg',
    'godot/icon.svg',
    'godot/scripts/**/*.gd',
    'godot/scenes/**',
    'godot/resources/**',
    'godot/data/**',
    'godot/assets/**',
    '!godot/**/*.import',
    // Documentation never reaches the artifact, so hashing it would stale a 48 MB
    // export over a doc edit. Evidence: the preset exports `all_resources` with an
    // empty include filter, a `.md` is not a Godot resource, and `strings` finds
    // zero README paths in the shipped pck.
    //
    // Note what is NOT evidence for this, because it was tried: rebuilding and
    // comparing pck hashes. THE PCK IS NOT BYTE-REPRODUCIBLE (see below), so a
    // hash change after any edit proves nothing at all.
    '!godot/**/*.md',
];

export function computeGodotExportFingerprint(rootDir) {
    const absoluteRoot = resolve(rootDir);
    const files = fg.sync(GODOT_EXPORT_SOURCE_PATTERNS, {
        cwd: absoluteRoot,
        onlyFiles: true,
        unique: true,
    });
    const normalizedFiles = [...files].sort();
    const hash = createHash('sha256');

    for (const file of normalizedFiles) {
        hash.update(file.replace(/\\/g, '/'));
        hash.update('\n');
        hash.update(readFileSync(resolve(absoluteRoot, file)));
        hash.update('\n');
    }

    return {
        algorithm: 'sha256',
        fileCount: normalizedFiles.length,
        value: hash.digest('hex'),
    };
}
