/**
 * Fingerprint the sources that feed the committed Godot web export.
 *
 * `railway.json` -> `deploy/web/Dockerfile` copies `output/web` straight into
 * Caddy, so WHATEVER IS IN THAT DIRECTORY IS THE LIVE GAME. It is produced by
 * running `bash godot/tools/build_web.sh` by hand and committing a ~23MB pack
 * plus a ~35MB wasm, and nothing checked that it matched `godot/**`. The
 * deployment silently drifted a whole feature behind the source once, and cost a
 * play session before anyone noticed.
 *
 * WHY A HASH AND NOT A TIMESTAMP
 * ------------------------------
 * The obvious check is "is index.pck older than the newest file under godot/".
 * That cannot work: git does not preserve mtimes, so a fresh clone stamps every
 * file with the checkout time and the comparison becomes noise. Content is the
 * only thing that survives a clone, so the build records a hash of its inputs
 * and `npm run validate` recomputes it.
 *
 * This mirrors tools/math_artifact_fingerprint.mjs, which does the same job for
 * the browser-smoke report.
 *
 * WHAT IS DELIBERATELY EXCLUDED
 * -----------------------------
 *   godot/build_info.json  a build stamp containing a timestamp, rewritten on
 *                          every build. Including it would make the fingerprint
 *                          change for reasons that are not source changes.
 *   godot/tests/**         never exported; a test edit does not stale the build.
 *   godot/tools/**         the build script itself is not shipped.
 *   any .import sidecar     regenerated by `godot --import`, so they churn
 *                          without the asset having changed.
 */
import { createHash } from 'crypto';
import { readFileSync } from 'fs';
import { resolve } from 'path';
import fg from 'fast-glob';

export const GODOT_EXPORT_SOURCE_PATTERNS = [
    'godot/project.godot',
    'godot/export_presets.cfg',
    'godot/icon.svg',
    'godot/scripts/**/*.gd',
    'godot/scenes/**',
    'godot/resources/**',
    'godot/data/**',
    'godot/assets/**',
    '!godot/**/*.import',
];

export function computeGodotExportFingerprint(rootDir) {
    const absoluteRoot = resolve(rootDir);
    const files = fg.sync(GODOT_EXPORT_SOURCE_PATTERNS, {
        cwd: absoluteRoot,
        onlyFiles: true,
        unique: true,
    });
    const normalizedFiles = [...files].sort();
    const hash = createHash('sha256');

    for (const file of normalizedFiles) {
        hash.update(file.replace(/\\/g, '/'));
        hash.update('\n');
        hash.update(readFileSync(resolve(absoluteRoot, file)));
        hash.update('\n');
    }

    return {
        algorithm: 'sha256',
        fileCount: normalizedFiles.length,
        value: hash.digest('hex'),
    };
}
