#!/usr/bin/env node
/**
 * Concept-ladder guard — the six ways a maths lesson can quietly become wrong.
 *
 * The ladder (godot/data/curriculum/concept_ladder.json) is the layer that turns a
 * curriculum step from a difficulty number into a teachable idea, and the
 * tutorials (godot/data/curriculum/tutorials.json) are the lessons it opens
 * with. Neither has a runtime that can tell you it is wrong: a tutorial that
 * teaches 7 + 3 = 11 renders perfectly, and a child believes it.
 *
 * So this checks, in order of how badly it would hurt:
 *
 *  1. THE MATHS. Every number a lesson asserts is recomputed from the picture
 *     it is drawn on. A ten-frame with seven and three in it must not claim
 *     eleven, and a guided question's correct answer must be the answer.
 *  2. STRUCTURE. Concept ranges are contiguous per domain from step 0, never
 *     overlap, and between them claim every step any problem is authored on.
 *  3. COVERAGE, against a declared baseline. A rung with no problems on it must
 *     be listed in knownGaps with a reason; a listed gap that has since been
 *     filled must be deleted. Same for thin rungs. A new hole cannot appear
 *     quietly and a closed one cannot linger as a lie. Then the same discipline
 *     for REACHABILITY: a concept whose every problem is filtered out by the
 *     owl's own operand cap must be declared in knownUnreachable, because a
 *     lesson no child can be served is a lesson that is not being reviewed.
 *  4. WIRING. Every concept's tutorial exists, every tutorial belongs to a
 *     concept, and every card names a visual tutorial_visual.gd can draw.
 *  5. WORDS. Every card and title has a string in every locale, and no
 *     tutorial.* string is left over from a card that no longer exists.
 *  6. FIT. Every string is measured against the box tutorial_tuning.json puts
 *     it in, so a layout change re-checks the copy that has to live in it.
 *  8. THE ANSWER'S POSITION. The guided try is a row of buttons in the authored
 *     order, so a fixed answer slot is a strategy that beats doing the maths.
 *
 * Also writes reports/math-concepts/coverage.json: the ladder, rung by rung,
 * with what is authored on each. That report is the answer to "what maths is
 * missing", and it is generated rather than remembered. The prose version lives
 * in docs/MATH_CONCEPT_LADDER.md, and check 7 holds that doc to the data:
 * every concept must appear in it, with its real step range.
 *
 * Run: node tools/validate_math_concepts.mjs
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'fs';
import { createHash } from 'node:crypto';
import { join, dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DATA = join(ROOT, 'godot', 'data');
const LOCALES = ['en', 'is'];
const REPORT_DIR = join(ROOT, 'reports', 'math-concepts');

/** Same monospace advance the i18n guard measures with; see tools/validate_i18n.mjs. */
const ADVANCE_RATIO = 0.63;

const failures = [];
const fail = (msg) => failures.push(msg);
const read = (path) => JSON.parse(readFileSync(path, 'utf8'));

const ladder = read(join(DATA, 'curriculum', 'concept_ladder.json'));
const tutorials = read(join(DATA, 'curriculum', 'tutorials.json'));
const tuning = read(join(DATA, 'tuning', 'tutorial_tuning.json'));
const strings = Object.fromEntries(
    LOCALES.map(l => [l, read(join(DATA, 'i18n', `strings_${l}.json`))]),
);

/**
 * The steps the derivation can actually EMIT, generated by
 * tools/gen_step_domains.ts. A step in `unreachable` is one no input can produce
 * -- deriveSubtractionStep maps operands of 20 or less onto 0..16 and the next
 * band starts at 21, so 17-20 are a dead zone in its range. Nine rungs were
 * recorded as authoring debt on exactly this basis and none of them was.
 *
 * Held apart from `knownGaps` on purpose: a gap is filled by writing problems, a
 * dead zone only by changing the derivation, and calling them the same thing
 * sent me looking for content that could never exist.
 */
const emittable = read(join(ROOT, 'reports', 'math-concepts', 'emittable-steps.json'));
const deadZone = (domain, step) => (emittable.domains?.[domain]?.unreachable ?? []).includes(step);

// A stale dead-zone report is the one failure mode that makes this guard lie:
// it would excuse a genuinely empty rung as structurally impossible. So hash the
// report's own payload together with what can change it -- the derivation and
// the pools -- and refuse to trust it unless the generator produced exactly
// this answer from exactly this code and content. Hashing only the inputs let a
// hand-edited `unreachable` list through; a negative test caught that.
{
    const hash = createHash('sha256');
    hash.update(JSON.stringify(emittable.domains)).update('\0');
    hash.update(readFileSync(join(ROOT, 'tools', 'math_curriculum.ts'), 'utf8'));
    hash.update(readFileSync(join(ROOT, 'tools', 'gen_step_domains.ts'), 'utf8'));
    for (const file of readdirSync(join(DATA, 'math')).filter(f => f.startsWith('problems_')).sort()) {
        hash.update(file).update('\0').update(readFileSync(join(DATA, 'math', file), 'utf8'));
    }
    // The Godot test mirrors this list as a GDScript constant, because a test
    // cannot read a file outside godot/data. A mirror that can drift is a
    // second source of truth, so hold the two together here.
    const gd = readFileSync(join(ROOT, 'godot', 'tests', 'test_concept_ladder.gd'), 'utf8');
    const block = gd.match(/const IMPOSSIBLE_RUNGS := \{([\s\S]*?)\n\}/);
    if (!block) {
        fail('test_concept_ladder.gd no longer declares IMPOSSIBLE_RUNGS, so nothing asserts the dead zones from inside the game.');
    } else {
        const mirrored = {};
        for (const [, domain, steps] of block[1].matchAll(/"([a-z_]+)":\s*\[([0-9,\s]*)\]/g)) {
            mirrored[domain] = steps.split(',').map(t => t.trim()).filter(Boolean).map(Number);
        }
        const measured = Object.fromEntries(Object.entries(emittable.domains ?? {})
            .filter(([, d]) => (d.unreachable ?? []).length > 0)
            .map(([k, d]) => [k, d.unreachable]));
        if (JSON.stringify(mirrored) !== JSON.stringify(measured)) {
            fail('test_concept_ladder.gd IMPOSSIBLE_RUNGS does not match the measured dead zones. '
                + `It says ${JSON.stringify(mirrored)}; the derivation says ${JSON.stringify(measured)}. `
                + 'Update the constant so the in-game assertion covers every dead zone.');
        }
    }

    if (emittable.inputsHash !== hash.digest('hex')) {
        fail('reports/math-concepts/emittable-steps.json is stale against the derivation or the pools. '
            + 'Every dead-zone exemption below is therefore unverified. Run: npx tsx tools/gen_step_domains.ts');
    }
}

const problems = [];
for (const file of readdirSync(join(DATA, 'math')).filter(f => f.startsWith('problems_'))) {
    for (const p of read(join(DATA, 'math', file)).problems ?? []) problems.push(p);
}

// ── 1. the maths ───────────────────────────────────────────────────────────

/**
 * What a picture actually shows, recomputed from its own parameters.
 *
 * This is the whole point of the file. Each visual has exactly one number it
 * asserts -- the total in the frame, where the hops land, the next term in the
 * pattern -- and every card that states that number, as a `result`, a `reveal`
 * or a guided question's `correct`, is checked against this rather than against
 * itself. Returns null for a picture that asserts nothing.
 */
function truthOf(visual, params) {
    const n = (key, fallback = 0) => Number(params[key] ?? fallback);
    switch (visual) {
        case 'count_all':
            return n('a') + n('b');
        case 'ten_frame':
            return n('filled') + n('second');
        case 'take_away':
            return n('total') - n('gone');
        case 'number_line':
            if (params.start === undefined) return null;
            return n('start') + n('hops');
        case 'balance':
            // A comparison card declares which way it is asking. Without `ask` the
            // card is a statement about the greater number, which is what every
            // balance card used to be -- and why "which is fewer" was unauthorable
            // even though 42% of the comparison pool asks exactly that.
            return params.ask === 'fewer' ? Math.min(n('a'), n('b')) : Math.max(n('a'), n('b'));
        case 'groups':
            return n('groups') * n('each');
        case 'part_whole':
            return n('total') - n('known');
        case 'tens_and_ones':
            return n('tens') * 10 + n('ones') + n('addTens') * 10 + n('addOnes') - n('takeOnes');
        case 'numbers': {
            const values = params.values ?? [];
            if (values.length < 2) return null;
            const gaps = new Set(values.slice(1).map((v, i) => v - values[i]));
            // A sequence with an uneven gap has no next term to assert. Better to
            // check nothing than to invent a rule the child cannot see.
            if (gaps.size !== 1) return null;
            return values[values.length - 1] + [...gaps][0];
        }
        case 'pattern_strip': {
            const core = params.core ?? [];
            if (core.length === 0) return null;
            return core[Number(params.length ?? core.length) % core.length];
        }
        case 'equation': {
            // Which slot is missing decides what the card asserts. A complete
            // sum asserts its result; anything else asserts the missing number.
            //   a op b            ->  a op b
            //   a + ? = c / c = a + ?  ->  c - a
            //   a - ? = c / c = a - ?  ->  a - c
            //   ? + b = c              ->  c - b
            //   ? - b = c / c = ? - b  ->  c + b
            const has = (k) => params[k] !== undefined;
            if (has('a') && has('b')) {
                switch (params.op) {
                    case '+': return n('a') + n('b');
                    case '-': return n('a') - n('b');
                    case '\u00D7': return n('a') * n('b');
                    case '\u00F7': return n('b') === 0 ? null : n('a') / n('b');
                    default: return null;
                }
            }
            // A missing operand asserts the number that fills it, recovered by
            // inverting the operator. Multiplicative shapes were added when the
            // relational overlays reached x and / : "2 x ? = 10" asserts 5, and
            // "? / 4 = 3" asserts 12, so both are checkable and neither may be
            // waved through as "asserts nothing".
            //   a + ? = c  ->  c - a       a x ? = c  ->  c / a
            //   a - ? = c  ->  a - c       a / ? = c  ->  a / c
            //   ? + b = c  ->  c - b       ? x b = c  ->  c / b
            //   ? - b = c  ->  c + b       ? / b = c  ->  c * b
            if (!has('result')) {
                return null;
            }
            const whole = (v) => (Number.isFinite(v) && Number.isInteger(v) ? v : null);
            if (has('a')) {
                switch (params.op) {
                    case '+': return n('result') - n('a');
                    case '-': return n('a') - n('result');
                    case '\u00D7': return n('a') === 0 ? null : whole(n('result') / n('a'));
                    case '\u00F7': return n('result') === 0 ? null : whole(n('a') / n('result'));
                    default: return null;
                }
            }
            if (has('b')) {
                switch (params.op) {
                    case '+': return n('result') - n('b');
                    case '-': return n('result') + n('b');
                    case '\u00D7': return n('b') === 0 ? null : whole(n('result') / n('b'));
                    case '\u00F7': return n('result') * n('b');
                    default: return null;
                }
            }
            return null;
        }
        default:
            return null;
    }
}

// ── 2. structure ───────────────────────────────────────────────────────────

/**
 * Base concepts partition their domain's steps; overlays claim problems by
 * authored skill instead (see _overlayComment in concept_ladder.json). Almost
 * every check below is about the PARTITION, so it must not see overlays -- an
 * overlay sharing a step range with a base concept is the normal case, not a
 * contiguity break.
 */
const isOverlay = (concept) => Boolean(concept.requires);
const baseConcepts = ladder.concepts.filter(c => !isOverlay(c));
const overlays = ladder.concepts.filter(isOverlay);

const MIN_PER_STEP = Number(ladder.gapPolicy?.minPerStep ?? 6);
/** An overlay has no steps to spread across, so it is held to a total instead. */
const MIN_OVERLAY_PROBLEMS = Number(ladder.gapPolicy?.minPerOverlay ?? 6);

/**
 * Which concept a problem belongs to, decided EXACTLY as
 * concept_ladder.gd::concept_for_problem decides it: overlay first, then the
 * step range. Two implementations of one rule is a bug waiting to happen, so
 * the shape is kept deliberately parallel and check 4b asserts they agree on
 * every authored problem.
 */
const overlayOf = (p) => overlays.find(
    o => o.domain === p.domain && (p.skills ?? []).includes(o.requires?.skill));

const byDomain = new Map();
for (const concept of baseConcepts) {
    if (!Array.isArray(concept.steps) || concept.steps.length !== 2) {
        fail(`[${concept.id}] steps must be a [low, high] pair`);
        continue;
    }
    const [lo, hi] = concept.steps;
    if (hi < lo) fail(`[${concept.id}] steps run backwards: [${lo}, ${hi}]`);
    if (!byDomain.has(concept.domain)) byDomain.set(concept.domain, []);
    byDomain.get(concept.domain).push(concept);
}

for (const [domain, concepts] of byDomain) {
    let expected = 0;
    for (const concept of concepts) {
        const [lo, hi] = concept.steps;
        if (lo !== expected) {
            fail(
                `[${concept.id}] starts at step ${lo}, but the previous concept in ${domain} `
                + `ends at ${expected - 1}. Concept ranges must be contiguous from step 0 -- a step `
                + `no concept claims is a step nothing can teach.`,
            );
        }
        expected = hi + 1;
    }
    const highest = Math.max(...problems.filter(p => p.domain === domain).map(p => p.curriculumStep ?? 0), -1);
    if (highest >= expected) {
        fail(
            `${domain} has problems authored up to step ${highest}, but its ladder stops at `
            + `${expected - 1}. Extend the last concept or add another.`,
        );
    }
}

const baseOf = (p) => (byDomain.get(p.domain) ?? []).find(
    c => p.curriculumStep >= c.steps[0] && p.curriculumStep <= c.steps[1]);
const conceptOf = (p) => overlayOf(p) ?? baseOf(p);
const problemsFor = (concept) => problems.filter(p => conceptOf(p) === concept);

// ── 2b. overlays ───────────────────────────────────────────────────────────
//
// An overlay earns its keep only if it actually claims problems and actually
// teaches them. A declared shape with nothing authored on it is a lesson about
// content that does not exist -- the same waste the unreachable check catches
// from the other direction.
for (const overlay of overlays) {
    const skill = overlay.requires?.skill;
    if (!skill) {
        fail(`[${overlay.id}] has a "requires" with no "skill". That is the only matcher supported today.`);
        continue;
    }
    const mine = problemsFor(overlay);
    if (mine.length < MIN_OVERLAY_PROBLEMS) {
        fail(
            `[${overlay.id}] claims skill "${skill}" but only ${mine.length} problem(s) carry it `
            + `(need ${MIN_OVERLAY_PROBLEMS}). A child cannot be given three different questions on it.`,
        );
    }
    if (!overlay.tutorial) {
        fail(`[${overlay.id}] is an overlay with no tutorial. Its whole purpose is to teach a shape the step ranges cannot see.`);
    }
    // The declared span is informative, not load-bearing -- but if it is wrong
    // the coverage report lies about where the content sits.
    const [lo, hi] = overlay.steps ?? [];
    for (const p of mine) {
        if (p.curriculumStep < lo || p.curriculumStep > hi) {
            fail(
                `[${overlay.id}] declares steps ${lo}-${hi} but ${p.id} sits on step ${p.curriculumStep}. `
                + `Widen the declared span or move the problem.`,
            );
            break;
        }
    }
    // Two overlays claiming one problem is ambiguous, and the runtime would
    // silently take whichever is listed first.
    for (const other of overlays) {
        if (other === overlay || other.domain !== overlay.domain) continue;
        if (other.requires?.skill === skill) {
            fail(`[${overlay.id}] and [${other.id}] both claim skill "${skill}" in ${overlay.domain}.`);
        }
    }
}

const orphans = problems.filter(p => {
    const concepts = byDomain.get(p.domain) ?? [];
    return !concepts.some(c => p.curriculumStep >= c.steps[0] && p.curriculumStep <= c.steps[1]);
});
for (const p of orphans.slice(0, 10)) {
    fail(`[${p.id}] is ${p.domain} step ${p.curriculumStep}, which no concept covers.`);
}
if (orphans.length > 10) fail(`...and ${orphans.length - 10} more problems no concept covers.`);

// ── 3. coverage against the declared baseline ──────────────────────────────


const countAt = (domain, step) =>
    problems.filter(p => p.domain === domain && p.curriculumStep === step).length;

const actualGaps = new Map();
const actualThin = new Map();
for (const concept of baseConcepts) {
    const [lo, hi] = concept.steps;
    for (let step = lo; step <= hi; step++) {
        if (deadZone(concept.domain, step)) {
            continue;
        }
        const n = countAt(concept.domain, step);
        const bucket = n === 0 ? actualGaps : (n < MIN_PER_STEP ? actualThin : null);
        if (!bucket) continue;
        if (!bucket.has(concept.domain)) bucket.set(concept.domain, new Set());
        bucket.get(concept.domain).add(step);
    }
}

function checkDeclared(label, declaredList, actual, advice) {
    const declared = new Map();
    for (const entry of declaredList ?? []) {
        if (!entry.why || String(entry.why).trim() === '') {
            fail(`${label} entry for ${entry.domain} has no "why". A gap without a reason is just a bug nobody wrote down.`);
        }
        if (!declared.has(entry.domain)) declared.set(entry.domain, new Set());
        for (const step of entry.steps ?? []) declared.get(entry.domain).add(step);
    }
    for (const [domain, steps] of actual) {
        for (const step of steps) {
            if (!declared.get(domain)?.has(step)) {
                fail(`${domain} step ${step} is ${label} and is not declared. ${advice}`);
            }
        }
    }
    for (const [domain, steps] of declared) {
        for (const step of steps) {
            if (deadZone(domain, step)) {
                fail(
                    `${domain} step ${step} is declared ${label}, but the derivation cannot emit it at all `
                    + `(see reports/math-concepts/emittable-steps.json). It is a dead zone, not authoring debt. `
                    + `Remove the declaration -- no problem can ever land there.`,
                );
                continue;
            }
            if (!actual.get(domain)?.has(step)) {
                fail(
                    `${domain} step ${step} is declared ${label} but no longer is `
                    + `(${countAt(domain, step)} problems authored). Delete it from concept_ladder.json -- `
                    + `a closed gap must not stay on the list.`,
                );
            }
        }
    }
}

checkDeclared('knownGaps', ladder.knownGaps, actualGaps,
    'Author problems for it, or add it to knownGaps in concept_ladder.json with a reason.');
checkDeclared('knownThin', ladder.knownThin, actualThin,
    `Author it up to ${MIN_PER_STEP} problems, or add it to knownThin in concept_ladder.json with a reason.`);

// ── 3b. can a child actually be given this concept? ───────────────────────
//
// Coverage above asks whether problems are AUTHORED on a rung. It never asked
// whether the owl can hand one over. The owl's selection config caps operand
// size, and math_problem_manager.gd / problem_pool_manager.gd drop any problem
// whose difficultyTraits.maxOperand exceeds it. Four concepts -- both two-digit
// concepts in addition and both in subtraction -- had a full lesson, ten strings
// per locale and a drawn representation, on maths no child can be served. The
// cap is read out of the component rather than restated, so raising it here
// closes these concepts and lowering it opens new ones, either way loudly.
const OWL_MAX_OPERAND = (() => {
    const src = readFileSync(join(ROOT, 'godot', 'scripts', 'entities', 'npc', 'math_challenge_component.gd'), 'utf8');
    const found = [...src.matchAll(/"maxOperand"\s*:\s*(\d+)/g)];
    if (found.length !== 1) {
        fail(
            `expected exactly one "maxOperand" literal in math_challenge_component.gd, found ${found.length}. `
            + 'The reachability check cannot tell which cap the owl uses, so it is not running.',
        );
        return Infinity;
    }
    return Number(found[0][1]);
})();

/** Whether the owl's operand cap lets this problem through at all. */
const servable = (p) => {
    const cap = p.difficultyTraits?.maxOperand;
    return cap === undefined || cap === null || Number(cap) <= OWL_MAX_OPERAND;
};

const actuallyUnreachable = new Set();
for (const concept of ladder.concepts) {
    const mine = problemsFor(concept);
    if (mine.length > 0 && !mine.some(servable)) actuallyUnreachable.add(concept.id);
}

{
    const declared = new Map();
    for (const entry of ladder.knownUnreachable ?? []) {
        if (!entry.why || String(entry.why).trim() === '') {
            fail(`knownUnreachable entry for ${entry.concept} has no "why". An unteachable lesson without a reason is just waste nobody wrote down.`);
        }
        declared.set(entry.concept, entry);
        if (!ladder.concepts.some(c => c.id === entry.concept)) {
            fail(`knownUnreachable names [${entry.concept}], which is not a concept.`);
        }
    }
    for (const id of actuallyUnreachable) {
        if (!declared.has(id)) {
            fail(
                `[${id}] has problems authored but not one of them survives the owl's operand cap of `
                + `${OWL_MAX_OPERAND}, so its lesson can never fire. Raise the cap, author problems inside it, `
                + `or declare it in knownUnreachable in concept_ladder.json with a reason.`,
            );
        }
    }
    for (const id of declared.keys()) {
        if (!actuallyUnreachable.has(id) && ladder.concepts.some(c => c.id === id)) {
            fail(
                `[${id}] is declared knownUnreachable but a child can now be served it. `
                + `Delete it from concept_ladder.json -- a lesson that reaches children must not stay on the list.`,
            );
        }
    }
}

// ── 4. wiring ──────────────────────────────────────────────────────────────

const tutorialById = new Map(tutorials.tutorials.map(t => [t.id, t]));
for (const concept of ladder.concepts) {
    if (!concept.tutorial) continue;
    if (!tutorialById.has(concept.tutorial)) {
        fail(`[${concept.id}] names tutorial "${concept.tutorial}", which is not in tutorials.json`);
    }
}
const claimed = new Set(ladder.concepts.map(c => c.tutorial).filter(Boolean));
for (const t of tutorials.tutorials) {
    if (!claimed.has(t.id)) fail(`tutorial [${t.id}] belongs to no concept. Wire it up or delete it.`);
}

/** The visuals tutorial_visual.gd can actually draw, read out of its own RENDERERS map. */
const rendererSource = readFileSync(join(ROOT, 'godot', 'scripts', 'ui', 'components', 'tutorial_visual.gd'), 'utf8');
const rendererBlock = rendererSource.slice(
    rendererSource.indexOf('const RENDERERS := {'),
    rendererSource.indexOf('}', rendererSource.indexOf('const RENDERERS := {')),
);
const drawable = new Set([...rendererBlock.matchAll(/"([a-z_]+)":\s*"_draw_/g)].map(m => m[1]));
if (drawable.size === 0) fail('could not read RENDERERS out of tutorial_visual.gd -- the visual check is not running');

// ── 5 + 6. words, and whether they fit ─────────────────────────────────────

const layout = tuning.layout ?? {};
/**
 * Each string's box, derived from the layout file rather than restated here, so
 * narrowing the board in tuning re-measures the copy that has to live in it.
 * Both labels wrap, so this is a "reads as three tidy lines" budget rather than
 * a clipping cliff -- generous, and it still catches a title nobody can read.
 */
const titleBox = {
    size: Number(layout.title_font_size ?? 30),
    // Board, less its padding, less the skip button and the gap before it.
    max: (Number(layout.board_min_w ?? 620) - 2 * Number(layout.padding ?? 26)
        - Number(layout.skip_button_w ?? 150) - Number(layout.separation ?? 16)) * 2,
    where: 'tutorial title, beside Skip, wrapping to at most two lines',
};
const bodyBox = {
    size: Number(layout.body_font_size ?? 22),
    max: Number(layout.body_wrap_width ?? 540) * 3,
    where: 'tutorial body, wrapping to at most three lines',
};

const expectedKeys = new Set(['tutorial.skip', 'tutorial.next', 'tutorial.back', 'tutorial.start', 'tutorial.nice']);
let measured = 0;

const measure = (key, box) => {
    for (const locale of LOCALES) {
        const value = strings[locale][key];
        if (value === undefined) {
            fail(`[${key}] is missing from strings_${locale}.json`);
            continue;
        }
        if (String(value).trim() === '') fail(`[${key}] is empty in strings_${locale}.json`);
        const width = String(value).length * box.size * ADVANCE_RATIO;
        measured++;
        if (width > box.max) {
            fail(
                `[${key}] in ${locale.toUpperCase()} needs ~${Math.round(width)}px in a `
                + `${box.max}px box (${box.where}). Shorten it, or widen the box in tutorial_tuning.json.`,
            );
        }
    }
};

for (const key of expectedKeys) measure(key, titleBox);

for (const tutorial of tutorials.tutorials) {
    const titleKey = `tutorial.${tutorial.id}.title`;
    expectedKeys.add(titleKey);
    measure(titleKey, titleBox);

    if ((tutorial.cards ?? []).length === 0) fail(`tutorial [${tutorial.id}] has no cards`);

    for (const [index, card] of (tutorial.cards ?? []).entries()) {
        const where = `${tutorial.id} card ${index + 1} (${card.body})`;

        if (!drawable.has(card.visual)) {
            fail(`${where} draws "${card.visual}", which tutorial_visual.gd has no renderer for.`);
        }

        const bodyKey = `tutorial.${tutorial.id}.${card.body}`;
        expectedKeys.add(bodyKey);
        measure(bodyKey, bodyBox);

        const truth = truthOf(card.visual, card.params ?? {});

        // A card that states an answer must state the true one -- but on an
        // unknown-slot form ("9 = 4 + ?", "? - 4 = 9") `result` is the other side
        // of the equals, not the answer.
        // `result` only states the answer when the sum is COMPLETE. With either
        // operand missing it is the other side of the equals, and cross-checking
        // it against the missing number compares two different things.
        const resultIsTheAnswer = card.visual !== 'equation'
            || (card.params?.a !== undefined && card.params?.b !== undefined);
        if (resultIsTheAnswer && card.params?.result !== undefined && truth !== null
            && Number(card.params.result) !== truth) {
            fail(`${where} shows the answer ${card.params.result}, but its own numbers make ${truth}.`);
        }
        if (card.params?.reveal !== undefined && truth !== null && Number(card.params.reveal) !== truth) {
            fail(`${where} reveals ${card.params.reveal}, but its own numbers make ${truth}.`);
        }

        // takeOnes greater than ones is a picture the renderer cannot draw: it
        // crosses the units it has and stops, so the drawing shows a bigger number
        // than the card's own parameters claim. Regrouping has no representation in
        // the set at all (see docs/MATH_CONCEPT_LADDER.md), so a card has to stay
        // inside one. Checked here rather than by returning a null truth, because a
        // null truth means "asserts nothing" and skips the result check entirely.
        if (card.visual === 'tens_and_ones' && Number(card.params?.takeOnes ?? 0) > Number(card.params?.ones ?? 0)) {
            fail(
                `${where} takes ${card.params.takeOnes} ones from ${card.params.ones ?? 0}. `
                + `tens_and_ones cannot draw a broken rod, so it would show `
                + `${Number(card.params.tens ?? 0) * 10} and assert something else.`,
            );
        }

        // A balance card highlights the tower it is ABOUT. On a question that is
        // the answer in colour, so a question must declare `ask` (which turns the
        // highlight off in tutorial_visual.gd) and a statement must not.
        if (card.visual === 'balance') {
            if (card.choice && !['more', 'fewer'].includes(card.params?.ask)) {
                fail(`${where} asks a balance question without params.ask ("more" or "fewer"). Without it the picture highlights its own answer.`);
            }
            if (!card.choice && card.params?.ask !== undefined) {
                fail(`${where} is a balance statement but declares params.ask. Only a question declares a direction.`);
            }
        }

        if (!card.choice) continue;
        const { options = [], correct } = card.choice;
        if (options.length < 2) fail(`${where} asks a question with fewer than two options.`);
        if (new Set(options.map(String)).size !== options.length) {
            fail(`${where} offers the same option twice.`);
        }
        if (!options.map(String).includes(String(correct))) {
            fail(`${where} marks ${correct} correct, but it is not one of the options.`);
        }
        if (truth === null) {
            fail(`${where} asks a question on a "${card.visual}" that asserts no answer, so nothing can check it.`);
        } else if (Number(correct) !== truth) {
            fail(`${where} marks ${correct} correct, but its own picture makes ${truth}.`);
        }
    }
}

// The last guided card is the child's turn: a lesson that never hands over is a
// lecture, and this pack's whole claim is that it does not give them.
for (const tutorial of tutorials.tutorials) {
    const cards = tutorial.cards ?? [];
    if (cards.length > 0 && !cards[cards.length - 1].choice) {
        fail(`tutorial [${tutorial.id}] ends without a question. The last card has to be the child's turn.`);
    }
    if (cards.slice(0, -1).some(c => c.choice)) {
        fail(`tutorial [${tutorial.id}] asks a question before the last card. Guided practice comes after the worked example, not during it.`);
    }
}

// ── 8. where the right answer sits ────────────────────────────────────────
//
// The guided try is the one moment in a lesson the child acts, and it is a row
// of buttons in the authored order. It used to be sorted ascending with the
// answer in the middle in 25 of 28 three-option lessons: a child who always
// tapped the middle button scored 25/28 and got the full celebration each time,
// having done no arithmetic. Position is a strategy, so it has to be a guard.
{
    const byWidth = new Map();
    for (const tutorial of tutorials.tutorials) {
        const cards = tutorial.cards ?? [];
        const choice = cards[cards.length - 1]?.choice;
        if (!choice) continue;
        const options = choice.options ?? [];
        const index = options.map(String).indexOf(String(choice.correct));
        if (index < 0) continue;
        if (!byWidth.has(options.length)) byWidth.set(options.length, []);
        byWidth.get(options.length).push(index);
    }
    for (const [width, indices] of byWidth) {
        // Allow real slack for a small set -- this is a "no tappable strategy"
        // floor, not a demand for a uniform distribution.
        const share = 0.55;
        const cap = Math.max(2, Math.ceil(indices.length * share));
        for (let slot = 0; slot < width; slot++) {
            const n = indices.filter(i => i === slot).length;
            if (n > cap) {
                fail(
                    `${n} of ${indices.length} guided tries with ${width} options put the correct answer `
                    + `in position ${slot + 1}, over the ${cap} allowed. Reorder some options in `
                    + `tutorials.json -- a fixed answer position is a strategy that beats the maths.`,
                );
            }
        }
    }
}

for (const locale of LOCALES) {
    for (const key of Object.keys(strings[locale])) {
        if (key.startsWith('tutorial.') && !expectedKeys.has(key)) {
            fail(`[${key}] is in strings_${locale}.json but no tutorial card uses it. Delete it from every locale.`);
        }
    }
}

// ── the report ─────────────────────────────────────────────────────────────

const rows = ladder.concepts.map(concept => {
    const [lo, hi] = concept.steps;
    // Attributed the way the runtime attributes: a problem an overlay claims is
    // NOT the base rung's, so a rung is never blamed for a skill it does not
    // teach. Counting by raw step range instead reported 17 phantom drifts the
    // moment the first overlay landed.
    const mine = problemsFor(concept);
    const steps = [];
    for (let step = lo; step <= hi; step++) {
        steps.push({ step, problems: mine.filter(p => p.curriculumStep === step).length });
    }
    const authored = new Set(mine.flatMap(p => p.skills ?? []));
    return {
        id: concept.id,
        domain: concept.domain,
        overlay: isOverlay(concept) ? concept.requires.skill : null,
        steps: concept.steps,
        tutorial: concept.tutorial ?? null,
        total: mine.length,
        // Only a rung can have an empty or thin STEP; an overlay owns no steps,
        // so reporting them for one would invent a gap that cannot exist.
        empty: isOverlay(concept) ? [] : steps.filter(s => s.problems === 0).map(s => s.step),
        thin: isOverlay(concept) ? [] : steps.filter(s => s.problems > 0 && s.problems < MIN_PER_STEP).map(s => s.step),
        perStep: steps,
        skillsAuthored: [...authored].sort(),
        skillsDeclared: [...(concept.skills ?? [])].sort(),
        servable: mine.filter(servable).length,
    };
});

// Drift between what a concept SAYS it covers and what is authored in its range
// is a warning, not a failure: the declared list is a design statement and the
// pools move underneath it. It still belongs in the report.
const skillDrift = rows.flatMap(row => [
    ...row.skillsAuthored.filter(s => !row.skillsDeclared.includes(s)).map(s => ({ concept: row.id, skill: s, state: 'authored but not declared' })),
    ...row.skillsDeclared.filter(s => !row.skillsAuthored.includes(s)).map(s => ({ concept: row.id, skill: s, state: 'declared but not authored' })),
]);

mkdirSync(REPORT_DIR, { recursive: true });
writeFileSync(join(REPORT_DIR, 'coverage.json'), JSON.stringify({
    generatedBy: 'tools/validate_math_concepts.mjs',
    minPerStep: MIN_PER_STEP,
    totalProblems: problems.length,
    concepts: rows,
    skillDrift,
}, null, 2) + '\n');

// ── 7. the doc that explains all this must still be describing it ─────────
//
// The numbers live in coverage.json, which is generated. The ladder's SHAPE --
// which concepts exist and which steps each one owns -- is a design decision,
// and it belongs in prose a human wrote. This check is what stops that prose
// from quietly becoming fiction.
const ONBOARDING_DOC = 'docs/MATH_CONCEPT_LADDER.md';

// The ladder doc states its shape as bare numbers, and bare numbers rot in
// silence: they claimed 40 concepts, 6 overlays, 18 empty rungs and 5 thin ones
// long after every one of those had changed. A new reader takes those on trust,
// so they are checked like any other assertion.
//
// This block used to read ONBOARDING_AGENT.md, which no longer exists — the doc
// set was consolidated, and the snapshot moved into the doc that describes the
// thing it counts. That is also the only reason the numbers survived the
// consolidation at all: every other count in prose was deleted, because nothing
// stopped it going stale. This one has this check.
{
    const onboarding = readFileSync(join(ROOT, ONBOARDING_DOC), 'utf8');
    const overlays = ladder.concepts.filter(c => c.requires);
    const withLesson = ladder.concepts.filter(c => c.tutorial);
    const deadSteps = Object.values(emittable.domains ?? {}).reduce((a, d) => a + (d.unreachable?.length ?? 0), 0);
    // The same two maps the summary line prints from, so the doc is checked
    // against exactly what the guard itself reports. Both already exclude dead
    // zones, because the sweep that fills them skips those.
    const emptyRungs = [...actualGaps.values()].reduce((a, set) => a + set.size, 0);
    const thinRungs = [...actualThin.values()].reduce((a, set) => a + set.size, 0);

    // Each count is matched WITH its label, not just looked for somewhere in
    // the file. A bare "does **9** appear anywhere" passes on any unrelated 9 in
    // the document -- a negative test caught exactly that, changing the overlay
    // count to a wrong number that the check waved through.
    const claims = [
        [`\\*\\*%d\\*\\* concepts`, ladder.concepts.length, 'concepts'],
        [`\\*\\*%d\\*\\* rungs keyed on step range`, ladder.concepts.length - overlays.length, 'step-keyed rungs'],
        [`\\*\\*%d\\*\\* overlays keyed on problem shape`, overlays.length, 'overlays'],
        [`of which \\*\\*%d\\*\\* open with a`, withLesson.length, 'concepts that open with a lesson'],
        [`\\*\\*%d\\*\\* lessons`, tutorials.tutorials.length, 'lessons'],
        [`\\*\\*%d\\*\\* cards`, tutorials.tutorials.reduce((a, t) => a + t.cards.length, 0), 'lesson cards'],
        [`\\*\\*%d\\*\\* empty`, emptyRungs, 'empty rungs'],
        [`\\*\\*%d\\*\\* thin rungs`, thinRungs, 'thin rungs'],
        [`\\*\\*%d\\*\\* concepts the cap`, (ladder.knownUnreachable ?? []).length, 'concepts the cap puts out of reach'],
        [`\\*\\*%d\\*\\* rungs are dead zones`, deadSteps, 'dead-zone rungs'],
    ];
    for (const [pattern, value, what] of claims) {
        const flatDoc = onboarding.replace(/\s+/g, ' ');
        if (!new RegExp(pattern.replace('%d', String(value))).test(flatDoc)) {
            const label = pattern.replace(/\\\*/g, '').replace('%d', 'N').trim();
            fail(`${ONBOARDING_DOC} does not say "${label.replace('N', String(value))}", `
                + `but ${value} is the current count of ${what}. Its ladder snapshot has gone stale.`);
        }
    }
}

const LADDER_DOC = 'docs/MATH_CONCEPT_LADDER.md';
{
    // Whitespace-normalised: the doc wraps its prose at 80 columns, so a
    // reason that matches perfectly still has newlines through the middle of it.
    // Dashes normalised too: prose typesets an aside with an em dash and JSON
    // data does not, and that difference is not a fact about the ladder.
    const flat = (text) => String(text).replace(/[\u2013\u2014]/g, '-').replace(/\s+/g, ' ');
    const doc = flat(readFileSync(join(ROOT, LADDER_DOC), 'utf8'));
    for (const concept of ladder.concepts) {
        if (!doc.includes(concept.id)) {
            fail(`${LADDER_DOC} does not mention concept [${concept.id}].`);
            continue;
        }
        const range = `${concept.steps[0]}-${concept.steps[1]}`;
        if (!doc.includes(range)) {
            fail(`${LADDER_DOC} does not give [${concept.id}] its step range ${range}.`);
        }
    }
    // Each declared gap's first sentence has to appear in the doc, so the
    // explanation a contributor reads is the one the data commits to.
    for (const gap of ladder.knownGaps ?? []) {
        const firstSentence = flat(gap.why).split(/(?<=\.)\s/)[0];
        if (!doc.includes(firstSentence)) {
            fail(
                `${LADDER_DOC} does not carry the reason declared for the ${gap.domain} gap `
                + `(looking for "${firstSentence}").`,
            );
        }
    }
    // Same for an unreachable concept: the most surprising fact about the ladder
    // is that four of its lessons cannot be shown, and a doc that omits it is
    // the reason nobody noticed for a whole session.
    for (const entry of ladder.knownUnreachable ?? []) {
        const firstSentence = flat(entry.why).split(/(?<=\.)\s/)[0];
        if (!doc.includes(firstSentence)) {
            fail(
                `${LADDER_DOC} does not carry the reason declared for [${entry.concept}] being unreachable `
                + `(looking for "${firstSentence}").`,
            );
        }
    }
}

// ── result ─────────────────────────────────────────────────────────────────

if (failures.length > 0) {
    console.error('concept ladder guard: FAILED');
    for (const f of failures) console.error(`  - ${f}`);
    process.exit(1);
}
const gapCount = [...actualGaps.values()].reduce((a, s) => a + s.size, 0);
const thinCount = [...actualThin.values()].reduce((a, s) => a + s.size, 0);
console.log(
    `concept ladder guard: clean (${ladder.concepts.length} concepts, ${tutorials.tutorials.length} tutorials, `
    + `${tutorials.tutorials.reduce((a, t) => a + t.cards.length, 0)} cards verified against their own arithmetic, `
    + `${measured} strings measured)`,
);
const deadCount = Object.values(emittable.domains ?? {}).reduce((a, d) => a + (d.unreachable?.length ?? 0), 0);
console.log(`  ${gapCount} empty rungs and ${thinCount} thin rungs, all declared -- see reports/math-concepts/coverage.json`);
console.log(`  ${deadCount} rungs the derivation cannot emit at all, excluded from both counts`);
console.log(
    `  operand cap ${OWL_MAX_OPERAND}: ${actuallyUnreachable.size} of ${ladder.concepts.length} concepts `
    + `cannot be served to a child, all declared`);
if (skillDrift.length > 0) console.log(`  ${skillDrift.length} skill-tag drifts reported (not fatal)`);
